### Numpy

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
list_of_lists=np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [12]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [28]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [39]:
np.random.rand(2,5)

array([[0.73135079, 0.47981264, 0.20876808, 0.02381905, 0.33081817],
       [0.53016947, 0.43850066, 0.50007631, 0.46825564, 0.14452586]])

In [49]:
np.random.randn(2,5)

array([[-0.0363897 , -0.06767875, -1.15039866,  0.44952917, -0.94896422],
       [ 2.255936  ,  0.33916223, -1.43488792,  0.01674782,  0.78067699]])

In [61]:
np.random.randint(1,10)

2

In [64]:
np.random.randint(20,56,100)

array([33, 31, 41, 51, 24, 43, 48, 51, 23, 50, 29, 55, 36, 44, 25, 32, 51,
       35, 26, 39, 34, 36, 41, 48, 21, 54, 22, 44, 31, 51, 38, 34, 42, 21,
       41, 34, 28, 28, 53, 43, 44, 36, 50, 38, 34, 27, 29, 41, 38, 25, 41,
       47, 50, 35, 42, 25, 32, 52, 22, 34, 51, 50, 25, 25, 48, 47, 48, 41,
       37, 20, 32, 36, 42, 50, 46, 33, 24, 28, 39, 22, 53, 24, 34, 41, 21,
       49, 35, 54, 36, 44, 48, 40, 23, 39, 27, 43, 28, 31, 41, 38])

In [65]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [66]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [67]:
sample_array.reshape(5,4)

ValueError: cannot reshape array of size 30 into shape (5,4)

In [69]:
rand_array=np.random.randint(0,100,20)
rand_array

array([15, 42, 34, 31, 99, 92, 29,  1, 13, 64,  2, 40, 51, 18, 25, 89, 11,
       72, 22, 69])

In [70]:
rand_array.min()

1

In [71]:
rand_array.max()

99

In [72]:
rand_array.argmin()

7

In [73]:
rand_array.argmax()

4

In [74]:
a=np.random.rand(2,3)
a

array([[0.36140459, 0.75808305, 0.59401518],
       [0.37968777, 0.130595  , 0.45309945]])

In [75]:
a.T

array([[0.36140459, 0.37968777],
       [0.75808305, 0.130595  ],
       [0.59401518, 0.45309945]])

In [76]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [79]:
sample_array[0]

10

In [81]:
sample_array[2:5]

array([12, 13, 14])

In [84]:
sample_matrix=np.array(([1,56,34],[34,54,87],[67,90,100]))

In [85]:
sample_matrix

array([[  1,  56,  34],
       [ 34,  54,  87],
       [ 67,  90, 100]])

In [89]:
sample_matrix[2][2]

100

In [92]:
sample_matrix[2]

array([ 67,  90, 100])

In [93]:
sample_matrix[1,:]

array([34, 54, 87])

In [94]:
sample_matrix[0,0:2]

array([ 1, 56])

In [100]:
sample_array=np.arange(1,10)

In [101]:
sample_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [103]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [104]:
np.min(sample_array)

1

In [105]:
np.max(sample_array)

9

In [ ]:
square root,
square,
exponential,
index of minimum
index of maximum
average
standard deviation
variance

In [106]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [107]:
np.square(sample_array)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [108]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [109]:
np.average(sample_array)

5.0

In [110]:
np.argmin(sample_array)

0

In [113]:
np.var(sample_array)

6.666666666666667

In [112]:
np.argmax(sample_array)

8

In [114]:
np.std(sample_array)

2.581988897471611

In [115]:
array=np.random.randn(3,6)
array

array([[-0.24380061, -0.19136046, -1.49856357,  1.11812209,  0.5787983 ,
         0.79924894],
       [-1.29724162, -0.07314913,  0.56867601, -1.11981538,  0.1229559 ,
        -1.77794807],
       [ 0.9048547 , -0.30018103, -1.78557428,  2.35804899, -0.08866326,
         0.70467942]])

In [116]:
np.round(array,decimals=2)

array([[-0.24, -0.19, -1.5 ,  1.12,  0.58,  0.8 ],
       [-1.3 , -0.07,  0.57, -1.12,  0.12, -1.78],
       [ 0.9 , -0.3 , -1.79,  2.36, -0.09,  0.7 ]])

In [120]:
sports=np.array(['golf','cricket','football','golf','basketball','Golf','Golf'])
np.unique(sports)

array(['Golf', 'basketball', 'cricket', 'football', 'golf'], dtype='<U10')

### Pandas

In [121]:
import pandas as pd

In [129]:
labels=['w','x','y','z']
sample_list=[1,2,3,4]
array=np.array([10,11,12,13])
dict={'a':1,'b':2,'y':3,'z':4}

In [125]:
pd.Series(data=array)

0    10
1    11
2    12
3    13
dtype: int32

In [126]:
pd.Series(data=sample_list,index=labels)

w    1
x    2
y    3
z    4
dtype: int64

In [127]:
pd.Series(array,labels)

w    10
x    11
y    12
z    13
dtype: int32

In [130]:
pd.Series(dict)

a    1
b    2
y    3
z    4
dtype: int64

In [131]:
sports1=pd.Series([1,2,3,4],index=["Cricket","Fball","Golf","Basketball"])
sports1

Cricket       1
Fball         2
Golf          3
Basketball    4
dtype: int64

In [132]:
sports2=pd.Series([11,21,5,6],index=["Cricket","Baseball","Golf","basketball"])
sports2

Cricket       11
Baseball      21
Golf           5
basketball     6
dtype: int64

In [133]:
sports1+sports2

Baseball       NaN
Basketball     NaN
Cricket       12.0
Fball          NaN
Golf           8.0
basketball     NaN
dtype: float64

In [135]:
df=pd.DataFrame(np.random.rand(6,5),index='A B C D E F'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())

In [136]:
df

Score1    Score2    Score3    Score4    Score5
A  0.429492  0.314668  0.371423  0.999083  0.357050
B  0.062298  0.467693  0.405734  0.046856  0.081142
C  0.012678  0.050383  0.806442  0.613962  0.328225
D  0.276479  0.906628  0.758814  0.915898  0.935689
E  0.954093  0.547799  0.127024  0.910909  0.819482
F  0.929253  0.780776  0.449439  0.334971  0.305655

In [139]:
df={'Id':[100,101,102,103],'Name':['a','b','c','d'],'Marks':[87,23,67,19]}
df1=pd.DataFrame(df)
df1

Id Name  Marks
0  100    a     87
1  101    b     23
2  102    c     67
3  103    d     19

In [140]:
import numpy as np
import pandas as pd

In [149]:
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/edForce/main/CardioGoodFitness-1.csv")

In [150]:
df

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
0     TM195   18    Male         14        Single      3        4   29562   
1     TM195   19    Male         15        Single      2        3   31836   
2     TM195   19  Female         14     Partnered      4        3   30699   
3     TM195   19    Male         12        Single      3        3   32973   
4     TM195   20    Male         13     Partnered      4        2   35247   
..      ...  ...     ...        ...           ...    ...      ...     ...   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   
178   TM798   47    Male         18     Partnered      4        5  104581   
179   TM798   48    Male         18     Partnered      4        5   95508   

     Miles  
0      112  
1       75  
2       66  
3       85  
4       47  
..     ...  
175    200  
176    200  
177    160  
178    120  
179    180  

[180 rows x 9 columns]

In [151]:
df.head()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47

In [152]:
df.head(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47
5   TM195   20  Female         14     Partnered      3        3   32973     66
6   TM195   21  Female         14     Partnered      3        3   35247     75
7   TM195   21    Male         13        Single      3        3   32973     85
8   TM195   21    Male         15        Single      5        4   35247    141
9   TM195   21  Female         15     Partnered      2        3   37521     85

In [153]:
df.sample()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
102   TM498   25  Female         14        Single      2        3   43206   

     Miles  
102     64

In [155]:
df.shape

(180, 9)

In [157]:
df.shape[1]

9

In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Product        180 non-null    object
 1   Age            180 non-null    int64 
 2   Gender         180 non-null    object
 3   Education      180 non-null    int64 
 4   MaritalStatus  180 non-null    object
 5   Usage          180 non-null    int64 
 6   Fitness        180 non-null    int64 
 7   Income         180 non-null    int64 
 8   Miles          180 non-null    int64 
dtypes: int64(6), object(3)
memory usage: 12.8+ KB


In [159]:
df.columns

Index(['Product', 'Age', 'Gender', 'Education', 'MaritalStatus', 'Usage',
       'Fitness', 'Income', 'Miles'],
      dtype='object')

In [160]:
df.dtypes

Product          object
Age               int64
Gender           object
Education         int64
MaritalStatus    object
Usage             int64
Fitness           int64
Income            int64
Miles             int64
dtype: object

In [161]:
df.describe()

Age   Education       Usage     Fitness         Income  \
count  180.000000  180.000000  180.000000  180.000000     180.000000   
mean    28.788889   15.572222    3.455556    3.311111   53719.577778   
std      6.943498    1.617055    1.084797    0.958869   16506.684226   
min     18.000000   12.000000    2.000000    1.000000   29562.000000   
25%     24.000000   14.000000    3.000000    3.000000   44058.750000   
50%     26.000000   16.000000    3.000000    3.000000   50596.500000   
75%     33.000000   16.000000    4.000000    4.000000   58668.000000   
max     50.000000   21.000000    7.000000    5.000000  104581.000000   

            Miles  
count  180.000000  
mean   103.194444  
std     51.863605  
min     21.000000  
25%     66.000000  
50%     94.000000  
75%    114.750000  
max    360.000000

In [162]:
df.describe(include="all")

Product         Age Gender   Education MaritalStatus       Usage  \
count      180  180.000000    180  180.000000           180  180.000000   
unique       3         NaN      2         NaN             2         NaN   
top      TM195         NaN   Male         NaN     Partnered         NaN   
freq        80         NaN    104         NaN           107         NaN   
mean       NaN   28.788889    NaN   15.572222           NaN    3.455556   
std        NaN    6.943498    NaN    1.617055           NaN    1.084797   
min        NaN   18.000000    NaN   12.000000           NaN    2.000000   
25%        NaN   24.000000    NaN   14.000000           NaN    3.000000   
50%        NaN   26.000000    NaN   16.000000           NaN    3.000000   
75%        NaN   33.000000    NaN   16.000000           NaN    4.000000   
max        NaN   50.000000    NaN   21.000000           NaN    7.000000   

           Fitness         Income       Miles  
count   180.000000     180.000000  180.000000  
unique         NaN            NaN         NaN  
top            NaN            NaN         NaN  
freq           NaN            NaN         NaN  
mean      3.311111   53719.577778  103.194444  
std       0.958869   16506.684226   51.863605  
min       1.000000   29562.000000   21.000000  
25%       3.000000   44058.750000   66.000000  
50%       3.000000   50596.500000   94.000000  
75%       4.000000   58668.000000  114.750000  
max       5.000000  104581.000000  360.000000